name: validar el script con ShellCheck

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Instalar Shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Ejecutasr shellCheck en script.sh
        run: shellcheck script.sh

